[package]
name = "nu_plugin_ratatui"
version = "0.0.0"
edition = "2024"
description = "Expose Ratatui user interfaces as Nushell commands"
license = "MIT"

[dependencies]
ansi-to-tui = "8.0.1"
nu-plugin = "0.116.1"
nu-protocol = "0.116.1"
qrcode = { version = "0.14.1", default-features = false }
ratatui = { version = "0.30.2", features = [] }
tachyonfx = { version = "0.25.2", default-features = false, features = ["std-duration"] }
tui-widgets = "0.7.12"
